# Generated by Django 4.1.3 on 2022-11-27 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verify',
            field=models.UUIDField(default=uuid.UUID('c38d3763-0ecd-4d22-96f0-6bced6a2dbfb')),
        ),
    ]
