# Generated by Django 4.1.3 on 2022-11-29 05:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verify',
            field=models.UUIDField(default=uuid.UUID('0209478c-931c-4a00-9820-6708a3227f07')),
        ),
    ]
