# Generated by Django 4.1.3 on 2022-11-22 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verify',
            field=models.UUIDField(default=uuid.UUID('88310e7b-b6c4-437b-8345-27103e941242')),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
