# Generated by Django 4.1.3 on 2022-11-29 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verify',
            field=models.UUIDField(default=uuid.UUID('6ec10008-e27d-44e7-a035-0f3f8fe08cd7')),
        ),
    ]
