# Generated by Django 4.1.3 on 2022-11-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_consult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consult',
        ),
    ]
