# Generated by Django 4.1.3 on 2022-11-29 13:10


from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verify',
<<<<<<< HEAD
            field=models.UUIDField(default=uuid.UUID('6ec10008-e27d-44e7-a035-0f3f8fe08cd7')),
=======
            field=models.UUIDField(default=uuid.UUID('c415c239-2e7b-4a68-aba9-3b7b98404612')),
>>>>>>> d71af058b35af49fc5fa803b88b86a7bd304307c
        ),
    ]
