# Generated by Django 4.1.3 on 2022-11-29 06:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verify',
            field=models.UUIDField(default=uuid.UUID('c415c239-2e7b-4a68-aba9-3b7b98404612')),
        ),
    ]
