# Generated by Django 4.1.3 on 2022-11-29 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verify',
            field=models.UUIDField(default=uuid.UUID('58a19476-5f79-4c44-82d7-0eb4a57ba59d')),
        ),
    ]
