# Generated by Django 4.1.3 on 2022-11-29 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0002_alter_comment_image_alter_entry_date_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('count_people', models.IntegerField()),
                ('price', models.IntegerField()),
                ('sender', models.CharField(max_length=50)),
                ('addressee', models.CharField(max_length=50)),
                ('tours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.tour')),
            ],
        ),
    ]
